# Generated by Django 5.2.4 on 2025-07-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinytrips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='textarea',
            new_name='message',
        ),
    ]
